/**
 * \file
 *
 * \brief Driver initialization.
 *
 (c) 2020 Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms,you may use this software and
    any derivatives exclusively with Microchip products.It is your responsibility
    to comply with third party license terms applicable to your use of third party
    software (including open source software) that may accompany Microchip software.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 */

/*
 * Code generated by START.
 *
 * This file will be overwritten when reconfiguring your START project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */

#include "driver_init.h"
#include <system.h>

void EVSYS_initialization(void)
{

	EVSYS_init();
}

/**
 * \brief System initialization
 */
void system_init()
{
	mcu_init();

	/* PORT setting on PA0 */

	// Set pin direction to output

	QTLP19_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	QTLP19_set_dir(PORT_DIR_OUT);

	/* PORT setting on PA1 */

	// Set pin direction to output

	QTLP20_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	QTLP20_set_dir(PORT_DIR_OUT);

	/* PORT setting on PA2 */

	// Set pin direction to output

	QTLP1_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	QTLP1_set_dir(PORT_DIR_OUT);

	/* PORT setting on PA3 */

	// Set pin direction to output

	QTLP2_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	QTLP2_set_dir(PORT_DIR_OUT);

	/* PORT setting on PA5 */

	// Set pin direction to output

	QTLP6_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	QTLP6_set_dir(PORT_DIR_OUT);

	/* PORT setting on PA6 */

	// Set pin direction to output

	QTLP7_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	QTLP7_set_dir(PORT_DIR_OUT);

	/* PORT setting on PB0 */

	// Set pin direction to output

	QTLP14_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	QTLP14_set_dir(PORT_DIR_OUT);

	/* PORT setting on PB1 */

	// Set pin direction to output

	QTLP13_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	QTLP13_set_dir(PORT_DIR_OUT);

	/* PORT setting on PB2 */

	// Set pin direction to output

	QTLP12_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	QTLP12_set_dir(PORT_DIR_OUT);

	/* PORT setting on PB3 */

	// Set pin direction to output

	QTLP11_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	QTLP11_set_dir(PORT_DIR_OUT);

	/* PORT setting on PB4 */

	// Set pin direction to output

	QTLP10_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	QTLP10_set_dir(PORT_DIR_OUT);

	/* PORT setting on PB5 */

	// Set pin direction to output

	QTLP9_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	QTLP9_set_dir(PORT_DIR_OUT);

	/* PORT setting on PC0 */

	// Set pin direction to output

	CHG_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	CHG_set_dir(PORT_DIR_OUT);

	/* PORT setting on PC1 */

	// Set pin direction to output

	WD_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	WD_set_dir(PORT_DIR_OUT);

	/* PORT setting on PC2 */

	// Set pin direction to output

	QTLP17_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	QTLP17_set_dir(PORT_DIR_OUT);

	/* PORT setting on PC3 */

	// Set pin direction to output

	QTLP18_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	QTLP18_set_dir(PORT_DIR_OUT);

	CLKCTRL_init();

	Timer_init();

	WDT_0_init();

	EVSYS_initialization();

	CPUINT_init();

	SLPCTRL_init();

	BOD_init();
}
